title: "Tutorial de GitHub"
description: "Guía colaborativa para dominar GitHub"
theme: just-the-docs

url: "https://jhojha.github.io"
baseurl: "/TUTORIAL-GITHUB"

search_enabled: true
nav_sort: case_insensitive
color_scheme: light

collections:
  pages:
    output: true
    permalink: /:path/

sass:
  sass_dir: assets/css
  style: compressed

include:
  - assets/css
