title: Tutorial de GitHub
description: Guía colaborativa para dominar GitHub
author: Jhon Villegas


url: "https://jhojha.github.io"
baseurl: "/TUTORIAL-GITHUB"  # Muy importante para que los enlaces funcionen correctamente


theme: jekyll-theme-minimal


sass:
  sass_dir: assets/css
  style: compressed


include:
  - assets/css


nav:
  - title: "Inicio"
    url: /
  - title: "Repositorio"
    url: https://github.com/JhoJha/TUTORIAL-GITHUB
  - title: "Ver TUTORIAL.md"
    url: /TUTORIAL.md
